name: Go Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
    paths-ignore:
      - web

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/bin/protoc
            ~/.cache
          key: livekit-egress

      - name: Build docker images
        run: docker build -t livekit-egress-test -f ./build/test/Dockerfile .

      - name: Run tests
        run: docker run --rm livekit-egress-test
